api-key: a3dc522fc4ae5bcb5b691538bf00587e
default:
  startTime: 10:00:00
  endTime: 18:00:00
startDay: 1
endDay: 3
url: http://api.openweathermap.org/data/2.5/forecast
description: Weather forecast for three days
